[package]
name = "apple-one"
version = "1.0.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r6502 = "1.1.1"
crossterm = "0.27"
